name: RPTS
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.7.2=haa95532_0
  - cudatoolkit=11.8.0=hd77b12b_0
  - cudnn=8.9.2.26=cuda11_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.14=h827c3e9_0
  - pip=24.2=py310haa95532_0
  - python=3.10.14=he1021f5_1
  - setuptools=72.1.0=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - tzdata=2024a=h04d1e81_0
  - vc=14.40=h2eaa2aa_0
  - vs2015_runtime=14.40.33807=h98bb1dd_0
  - wheel=0.43.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.4.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - colorama==0.4.6
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - filelock==3.13.1
      - fsspec==2024.6.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.5
      - idna==3.4
      - jinja2==3.1.3
      - jiter==0.5.0
      - joblib==1.4.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - openai==1.41.0
      - packaging==24.1
      - pillow==10.4.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyyaml==6.0.2
      - regex==2024.7.24
      - requests==2.28.1
      - safetensors==0.4.4
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - sentence-transformers==3.0.1
      - sniffio==1.3.1
      - sympy==1.12
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.0.0+cu118
      - torchaudio==2.0.1+cu118
      - torchvision==0.15.1+cu118
      - tqdm==4.66.5
      - transformers==4.44.0
      - typing-extensions==4.12.2
      - urllib3==1.26.13
prefix: D:\miniconda\envs\RPTS
